config/routes.rb
Rms::Application.routes.draw do
  devise_for :users

  root :to => 'homes#index'

  resources :clients 
  resources :brands
  resources :branches
  resources :users
  resources :user_roles
  resources :permissions

  match '/setup', :to => "clients#index"
  match '/organization', :to => "clients#index"
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  attr_accessible :name, :brand_id , :address1, :address2, :city, :zip, :province_state, :country, :status,
  :photo_file_name, :photo_content_type, :photo_file_size,:photo_updated_at, :photo
  

  has_attached_file :photo,
  :default_url => '/assets/images/company.png'

  belongs_to :brand
  validates :name, :presence => true
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :name, :client_id, :description,:photo_file_name,:photo_content_type,
  :photo_file_size,:photo_updated_at,:photo
  

  has_attached_file :photo,
  :default_url => '/assets/icons/company.png'

  belongs_to :client
  has_many :branches
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible  :name,:description, :status,:photo_file_name, :photo_content_type, :photo_file_size,:photo_updated_at, :photo, :user_id

  has_attached_file :photo,
  :default_url => '/assets/icons/company.png'
  belongs_to :user
  has_many :brands
end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  
  attr_accessible :user_role_id, :company_module, :restaurant_module, :branch_module, :role_module

  has_many :roles
  belongs_to :company
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :branch_id, :company_id, :restaurant_id, :role_name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
   
  attr_accessible :email, :password, :password_confirmation, :remember_me,:first_name, :last_name,
   :confirmed_at, :confirmation_token, :confirmation_sent_at, :unconfirmed_email, :mobile, :username, :status, :login
  
  attr_accessor :login
  
 
  has_one :client
  #logging in using username
  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
  end




end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  validates :name, :presence => true
  attr_accessible :name

  belongs_to :company
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

	def index
    @clients = Client.find(:all, :conditions => { :user_id => current_user.id } )
    @showidClient = Client.find(:all, :conditions => { :user_id => current_user.id }).first
    @brand = Brand.new
    @brands = Brand.all
    @showBranches = Branch.all
    @branch = Branch.new
    
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @brands }
    end
 
  end

  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @brand }
    end
  end

 

  def edit
    @brand = Brand.find(params[:id])
  end

  def create
    @brand = Brand.new(params[:brand])
    respond_to do |format|
      if @brand.save
        format.html { redirect_to(brands_path, :notice => 'Brand was successfully created.') }
        format.xml  { render :xml => @brand, :status => :created, :location => @brand }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @brand.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brands])
        format.html { redirect_to(@brand, :notice => 'Brand was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @brand.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to(brands_path, :notice => 'Brand has been deleted.') }
      format.xml  { head :ok }
    end
  end	


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	
	def index
		 if user_signed_in?
		 
		 else	
	  		redirect_to new_user_session_path
	  	 end
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		 respond_to do |format|
			if @user.save
				 format.html { redirect_to(users_path, :notice => 'Company users was successfully created.') }
				 format.xml  { render :xml => @roles, :status => :created, :location => @roles }			 
			else
				format.html { render :action => "new" }
         		format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
			end
		end
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/company_users_helper.rb
module CompanyUsersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>

  <fieldset>
  	<%= f.hidden_field :company_id %>
  	<%= f.hidden_field :restaurant_id %>
    <%= f.hidden_field :branch_id %>
    <%= f.input :first_name, :required=>true %>
    <%= f.input :last_name, :required=>true %>
    <%= f.input :email, :required=>true %>
    <%= f.input :password, :required=>true %>
  </fieldset>

  <%= f.button :submit, :class => "btn btn-inverse" %>
<% end %>

app/views/users/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <%= render 'layouts/sidebar'%>
  

    <div class="span8">
      <div class="well row-fluid">   
    <legend><h2>User Accounts</h2></legend>

       <% flash.each do |name, msg| %>
            <div class="alert alert-<%= name == :notice ? "success"  : "error" %>">
              <a class="close" data-dismiss="alert">x</a>
              <%= msg %>
            </div>
          <% end %>
          <%= link_to 'Add Company Personnel',new_user_path,  :class => "btn btn-inverse" %>
        <br/>
        <br/>
          <table class="table table-striped">
                <tr>

                  <th>Name</th>
                  <th>Role Name</th>
                  <th>Email</th>
                  <th>Actions</th>
                
                </tr>
                 
                      <tr>
                        <td></td> 
                        <td></td> 
                        <td></td>
                        <td></td>
                      </tr>
                 
          </table>
    

      </div>
  </div>


    
  </div>
</div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container-fluid">
  <div class="row-fluid">
  	<%= render 'layouts/sidebar'%>

    <div class="span8">
	  <div class="well row-fluid">	 	
 		<legend><h2>Add Company Personnel</h2></legend>
		<br>
			<%= render 'form' %>
	  </div>
	</div>
  </div>
</div>