config/routes.rb
Rms::Application.routes.draw do
  devise_for :users

  root :to => 'homes#index'

  resources :clients 
  resources :brands
  resources :branches
  resources :users
  resources :user_roles
  resources :permissions

  match '/setup', :to => "clients#index"
  match '/organization', :to => "clients#index"
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  attr_accessible :name, :brand_id , :address1, :address2, :city, :zip, :province_state, :country, :status,
  :photo_file_name, :photo_content_type, :photo_file_size,:photo_updated_at, :photo
  

  has_attached_file :photo,
  :default_url => '/assets/images/company.png'

  belongs_to :brand
  validates :name, :presence => true
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :name, :client_id, :description,:photo_file_name,:photo_content_type,
  :photo_file_size,:photo_updated_at,:photo
  

  has_attached_file :photo,
  :default_url => '/assets/icons/company.png'

  belongs_to :client
  has_many :branches
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible  :name,:description, :status,:photo_file_name, :photo_content_type, :photo_file_size,:photo_updated_at, :photo, :user_id

  has_attached_file :photo,
  :default_url => '/assets/icons/company.png'
  belongs_to :user
  has_many :brands
end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  
  attr_accessible :user_role_id, :company_module, :restaurant_module, :branch_module, :role_module

  has_many :roles
  belongs_to :company
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :branch_id, :company_id, :restaurant_id, :role_name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
   
  attr_accessible :email, :password, :password_confirmation, :remember_me,:first_name, :last_name,
   :confirmed_at, :confirmation_token, :confirmation_sent_at, :unconfirmed_email, :mobile, :username, :status, :login
  
  attr_accessor :login
  
 
  has_one :client
  #logging in using username
  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
  end




end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  validates :name, :presence => true
  attr_accessible :name

  belongs_to :company
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

	def index
    @clients = Client.find(:all, :conditions => { :user_id => current_user.id } )
    @showidClient = Client.find(:all, :conditions => { :user_id => current_user.id }).first
    @brand = Brand.new
    @brands = Brand.all
    @showBranches = Branch.all
    @branch = Branch.new
    
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @brands }
    end
 
  end

  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @brand }
    end
  end

 

  def edit
    @brand = Brand.find(params[:id])
  end

  def create
    @brand = Brand.new(params[:brand])
    respond_to do |format|
      if @brand.save
        format.html { redirect_to(brands_path, :notice => 'Brand was successfully created.') }
        format.xml  { render :xml => @brand, :status => :created, :location => @brand }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @brand.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brands])
        format.html { redirect_to(@brand, :notice => 'Brand was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @brand.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to(brands_path, :notice => 'Brand has been deleted.') }
      format.xml  { head :ok }
    end
  end	


end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController


	def index
		@client = Client.new 
	 	@clients = Client.all
	end
    
	def new
		@client = Client.new 
	end


  

	def create
		@client = Client.new(params[:client])
		 respond_to do |format|
			if @client.save
				 format.html { redirect_to(clients_path, :notice => 'Company was successfully created.') }
				 format.xml  { render :xml => @client, :status => :created, :location => @client }
			else
				 format.html { render :action => "new" }
       			 format.xml  { render :xml => @client.errors, :status => :unprocessable_entity }
			end
		end
	end

	def edit
		@client = Client.find(params[:id])	
	end

	def update
	  @client = Client.find(params[:id])
      respond_to do |format|
	      if @client.update_attributes(params[:client])
	        format.html { redirect_to(clients_path, :notice => 'Company was successfully updated.') }
	        format.xml  { head :ok }
	      else
	        format.html { render :action => "edit" }
	        format.xml  { render :xml => @client.errors, :status => :unprocessable_entity }
	      end
   	  end
	end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	
	def index
		 if user_signed_in?
		 
		 else	
	  		redirect_to new_user_session_path
	  	 end
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		 respond_to do |format|
			if @user.save
				 format.html { redirect_to(users_path, :notice => 'Company users was successfully created.') }
				 format.xml  { render :xml => @roles, :status => :created, :location => @roles }			 
			else
				format.html { render :action => "new" }
         		format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
			end
		end
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/company_users_helper.rb
module CompanyUsersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/brands/_form.html.erb
<div class="modal hide fade" id="brand">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Create a brand</h3>
    
  </div>
  <div class="modal-body">
   <%= simple_form_for @brand do |f|%>
      <fieldset>
        <%= f.label "Brand logo "%>
        <%= f.file_field :photo %>
        <%= f.input :name, :label => 'Brand Name' %>
        <%= f.input :description, :as => :text, :input_html => { :rows => 3, :cols => 25, :class => 'resizable' }, :label => "Description"  %>
        <%= f.hidden_field :client_id, :value=>  @showidClient.id %>
      </fieldset>
      <br/>
         <div class="modal-footer">
            <%= f.button :submit, :class => "btn btn-primary" %>
            <button type="button" class="btn" data-dismiss="modal">Back</button>
        </div>
   <%end%> 
    

 </div>
</div>

app/views/brands/_showbrands.html.erb
 <div class="brand-level">

 	 <% @brandid = "" %>
     <% @brands.each do |b| %>
     
     	<table>
     		<tr>
     			<td>
	     			<%= image_tag b.photo.url %>
	     		</td>
     			<td width="750">
	     			<h2><%= b.name %>&nbsp;<%= b.id %></h2>
	     		</td>
	     		<td>
	     			<%= link_to "Edit", edit_brand_path(b.id) %>&nbsp;
	     		</td>
	     		<td>
	     			|&nbsp;
	     		</td>
	     		<td>
	     			<%= link_to "Delete", b, :confirm => "Are you sure?", :method => :delete %>
	     		</td>
     		</tr>
     	</table>
	     
	    <p><%= b.description %></p>
	    <div class="droppable-area">
	      	<ul class="set-permission-group">
	      		
	      				<% @showBranches.each do |sb|%>
			      		 	<% if sb.brand_id == b.id %>
			    
									<%= sb.name %>
				
							<%end%>
	      				<%end%>
	      		
	      		
				
				<%= link_to "", :data => {:toggle => "modal", :target => "#branch" + b.id.to_s } do %>
						<%= image_tag("/assets/icons/add.png")%>
				<%end%>
	      	</ul>
      	<div class="clear-floats"></div></div>
     
      	<% @brandid = b.id %>
      	<% @modalId = "branch" + b.id.to_s %>
		<%= render :template => "branches/_form" %>
		

     <%end%>
</div>

app/views/brands/index.html.erb
<div class="fill-all container-fluid">
  <div class="row-fluid">
         <%= render 'layouts/sidebar'%>

      <div class="span" id="content">
        
          <div class="span11">


           <%= render 'layouts/setuptabs'%>
            
            <div class="hero-unit">
              <% if @clients.count > 0 %>
                <%= render 'form' %>
                <button class="btn btn-primary" data-toggle="modal" href="#brand">Create a Brand</button>  
              <br/>
                <%= render 'showbrands' %>
              <%else%>
                 <h1>Cannot create a brand</h1>
                  <p>You need to create a client.</p>
                  <p>
                    <%= link_to "Create a client", clients_path, :class => "btn btn-info"%>
                  </p>
              <%end%>
            </div>  

        </div> <!-- END SPAN11 -->
      </div> <!-- END SPAN CONTENT -->
    </div>
</div>

app/views/clients/_form.html.erb
<div class="modal hide fade" id="client">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Create a client</h3>
    
  </div>
  <div class="modal-body">

    <%= simple_form_for @client do |f| %>
      <fieldset>
        <%= f.label "Client logo "%>
        <%= f.file_field :photo %>
        <%= f.input :name, :label => 'Client name' %>
        
        <%= f.hidden_field :user_id, :value => current_user.id %>
      </fieldset>
      <br/>
         <div class="modal-footer">
            <%= f.button :submit, :class => "btn btn-primary" %>
            <button type="button" class="btn" data-dismiss="modal">Back</button>
        </div>
    <% end %>

 </div>
</div>

<div class="modal hide fade" id="clientEdit">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Edit a client</h3>
    
  </div>
  <div class="modal-body" id="clientEditBody">

    <%= simple_form_for @client do |f| %>
  <fieldset>
    <%= f.label "Client Photo"%>
    <%= f.file_field :photo %>  
    <%= f.input :name, :label => 'Client name' %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </fieldset>
  <br/>
     <div class="modal-footer">
        <%= f.button :submit, :class => "btn btn-primary" %>
        <button type="button" class="btn" data-dismiss="modal">Back</button>
    </div>
<% end %>

 </div>
</div>

app/views/clients/_showclient.html.erb
<div class="hero-unit">
	 <% @clients.each do |c| %>
     
     <%= image_tag c.photo.url %><h2><%= c.name%></h2>
     
     <p><%= c.description %></p>
     <div class="droppable-area">
      <ul class="set-permission-group">
        <li></li>
      </ul>
      <div class="clear-floats"></div></div>

     <%end%>
</div>

app/views/clients/index.html.erb
<div class="fill-all container-fluid">
	<div class="row-fluid">
         <%= render 'layouts/sidebar'%>

    	<div class="span" id="content">
     		
     			<div class="span11">


				  	 		 <%= render 'layouts/setuptabs'%>
					  
						
							<% if @clients.count > 0 %>
								<%= render 'showclient' %>
							<%else%>
							<div class="hero-unit">
								<%= render 'form' %>
							   <h1>Create a Client</h1>
									<p>Establish your company</p>
									<p>
										<button class="btn btn-primary" data-toggle="modal" href="#client">Create Client</button>	
									</p>
							</div>
							<%end%>		

				</div> <!-- END SPAN11 -->


        </div> <!-- END SPAN CONTENT -->

    </div>
</div>

app/views/homes/_landing.html.erb
<div class="container">
  <div class="row-fluid">
  	<% flash.each do |name, msg| %>
			  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
			    <a class="close" data-dismiss="alert">×</a>
			    <%= msg %>
			  </div>
	<% end %>
	 
  	MARKETING PAGE
  </div>
</div>

app/views/homes/index.html.erb
<div class="container">
  <div class="row-fluid">
  	<% flash.each do |name, msg| %>
			  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
			    <a class="close" data-dismiss="alert">×</a>
			    <%= msg %>
			  </div>
			<% end %>
  	DASHBOARD
  </div>
</div>