config/routes.rb
Rms::Application.routes.draw do
  devise_for :users

  root :to => 'homes#index'

  resources :clients 
  resources :brands
  resources :branches
  resources :users
  resources :user_roles
  resources :permissions

  match '/setup', :to => "clients#index"
  match '/organization', :to => "clients#index"
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  attr_accessible :name, :brand_id , :address1, :address2, :city, :zip, :province_state, :country, :status,
  :photo_file_name, :photo_content_type, :photo_file_size,:photo_updated_at, :photo
  

  has_attached_file :photo,
  :default_url => '/assets/images/company.png'

  belongs_to :brand
  validates :name, :presence => true
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :name, :client_id, :description,:photo_file_name,:photo_content_type,
  :photo_file_size,:photo_updated_at,:photo
  

  has_attached_file :photo,
  :default_url => '/assets/icons/company.png'

  belongs_to :client
  has_many :branches
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible  :name,:description, :status,:photo_file_name, :photo_content_type, :photo_file_size,:photo_updated_at, :photo, :user_id

  has_attached_file :photo,
  :default_url => '/assets/icons/company.png'
  belongs_to :user
  has_many :brands
end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  
  attr_accessible :user_role_id, :company_module, :restaurant_module, :branch_module, :role_module

  has_many :roles
  belongs_to :company
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :branch_id, :company_id, :restaurant_id, :role_name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
   
  attr_accessible :email, :password, :password_confirmation, :remember_me,:first_name, :last_name,
   :confirmed_at, :confirmation_token, :confirmation_sent_at, :unconfirmed_email, :mobile, :username, :status, :login
  
  attr_accessor :login
  
 
  has_one :client
  #logging in using username
  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
  end




end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  validates :name, :presence => true
  attr_accessible :name

  belongs_to :company
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	
	def index
		 if user_signed_in?
		 
		 else	
	  		redirect_to new_user_session_path
	  	 end
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		 respond_to do |format|
			if @user.save
				 format.html { redirect_to(users_path, :notice => 'Company users was successfully created.') }
				 format.xml  { render :xml => @roles, :status => :created, :location => @roles }			 
			else
				format.html { render :action => "new" }
         		format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
			end
		end
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/layouts/_client_fields.html.erb
<div class="nested-fields">
    <%= client.text_field :name %>
</div>

app/views/layouts/_header.html.erb
<!-- SIGN IN -->
<section class="slide" id="fliptrip-login" data-section="3" class="span12 login-window">

  <div class="container" id="login-container">
     
      <div class="span9 offset1">
	    <h2>Sign In</h2>
    	  <div class="pull-right">
     
      	  </div> <!-- pull-right -->
   	  </div> <!-- span9 offset1 -->

      <div class="span4">
              <%= render :template => 'devise/sessions/new'%>
              <div class="homeform-align">
               
             
                       
                        <a href="javascript:{}" data-section="4" class="links tableft" id="forgot-button">Forgot your password?</a>   
                        <br/>
                         <a href="javascript:{}" data-section="5" class="links tableft" id="confirm-button">Send me email confirmation</a>   

           	
   			  </div> <!-- homeform-align -->
  		</div> <!-- span4 -->
    
   </div> <!-- container -->
</section>
<!-- END SIGN IN -->




        

<!-- SIGN UP -->        
<section class="slide" id="fliptrip-join" data-section="2" class="span12 login-window">
    <div class="container">   
        <div class="span9 offset1">
          		<h2>Sign Up</h2>
           	<div class="pull-right">
          		<a href="javascript:{}" data-section="1" class="close-icon" id="hide-join-button">X</a>
        	</div> <!-- pull right -->
        </div> <!-- span9 offset1 -->
        
       
        <div class="span4">      

           <%= render :template => 'devise/registrations/new'%>


        </div> <!-- span4 -->
    </div> <!-- container -->
</section>
<!-- END SIGN UP -->

<!-- FORGOT PASSWORD -->
<section class="slide" id="fliptrip-forgot" data-section="4" class="span12 login-window">
      
      <div class="container">

        <div class="span9 offset1">
            <h2>Forgot Password</h2>
          <div class="pull-right">
            <a href="javascript:{}" data-section="1" class="close-icon" id="hide-forgot-button">X</a>
          </div> <!-- pull-right -->
        </div> <!-- span9 offset1 -->

       
        <div class="span4">
           <%= render :template => 'devise/passwords/new'%>
        </div> <!-- span4 -->

</section>
<!-- END FORGOT PASSWORD -->



<!-- CONFIRMATION EMAIL -->
<section class="slide" id="fliptrip-confirm" data-section="5" class="span12 login-window">
      <div class="container">

        <div class="span9 offset1">
            <h2>Confirm Email</h2>
          <div class="pull-right">
            <a href="javascript:{}" data-section="1" class="close-icon" id="hide-confirm-button"><%= image_tag "icons/close.png" %></a>
          </div> <!-- pull-right -->
        </div> <!-- span9 offset1 -->

      

        <div class="span4">          
        
              <%= render :template => 'devise/confirmations/new'%>
        </div> <!-- span4 -->

</section>
<!-- END CONFIRMATION EMAIL -->





  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
         
        </a>
        <%= link_to "RESTOBOT", root_path, :class => "brand" %>
         <div class="pull-right2">
          <div class="nav-collapse">
            <ul class="nav">
              <li <% if current_page?(new_user_registration_path) %> class="active" <% end %> > <a href="javascript:{}" data-section="2" class="link-transit" id="join-button">Sign Up</a></li>
              <li><a href="javascript:{}" data-section="3" class="link-transit" id="login-button">Login</a></li>
            </ul>
          </div>
        </div>

      </div>
    </div>
  </div>

app/views/layouts/_header2.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "RESTOBOT", root_path, :class => "brand" %>

        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Setup", setup_path, :class => "inventoryAnchor"  %></li>
            <li><%= link_to "Inventory" %></li>
          </ul>
        </div>
          <div>
          <div class="dropdown pull-right">
            
            <a class="dropdown-toggle" data-toggle="dropdown" href="" >
                <i class="icon-user"></i><%= current_user.email %>
                <span class="caret"></span>
            </a>
            
            <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
                <li><%= link_to "Profile" %></i></li>
                  <li class="divider"></li>
                  <li><%= link_to "Account Settings",edit_user_registration_path%></li>
                  <li class="divider"></li>
                  <li><%= link_to "Log Out",destroy_user_session_path, :method => :delete %></li>
            </ul>
          </div>
          </div>


      </div>
    </div>
  </div>

app/views/layouts/_setuptabs.html.erb
  <ul class="nav nav-tabs">
                <li
                	<% if current_page?(clients_path) %> 	
                        class="active"  
                    <% elsif current_page?(setup_path) %>     
                        class="active"  
                    <%end%> 
                    ><%= link_to "Company", clients_path %></li>
                <li
                	<%if current_page?(brands_path) %> 
                    	class="active"  
                    	<%end%>
                      ><%= link_to "Brands and Branches", brands_path %></li>
              
                <li
                	<%if current_page?(permissions_path) %> 
                    	class="active"  
                    	<%end%>
                	  ><%= link_to "Permissions", permissions_path%></li>
  </ul>

app/views/layouts/_sidebar.html.erb
<div id="sidebar-area" class="span2">
     <legend>Setup</legend>
        <ul class="sidebar">
            <li 
                <% if current_page?(clients_path) %> 
                    class="active" 
                <% elsif current_page?(setup_path)%>
                	class="active" 
                <%elsif current_page?(permissions_path)%>
                	class="active"
                <%elsif current_page?(organization_path)%>
                	class="active"	
                <%elsif current_page?(branches_path)%>
                    class="active"  
                <%elsif current_page?(brands_path)%>
                    class="active"  
                <% end %>
            >
                <div class="sub-menu-item"><%= link_to "Organization", organization_path %>
            </li>

            <li>
                <div class="sub-menu-item"><%= link_to "Inventory" %>
            </li>  
               
        </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rms</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<% if user_signed_in? %> 

  <body style="overflow: hidden;">

      <%= render "layouts/header2" %>
      <%= yield %>

  </body>

<% else %>

  <body style="padding-top: 0;">
    <%= render "layouts/header" %>
    <div style="padding-top: 80px;">
      <%= render "homes/landing" %>
    </div>
  </body>

<% end %>